/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gatewayguiswing;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author blunt
 */
public class DoctorContact extends javax.swing.JFrame {

    /**
     * Creates new form DoctorContact
     */
    public DoctorContact() {
        initComponents();
        this.setResizable(false);
        List<String> s = getOutboxMail();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < s.size(); i++) {
                model.addElement(s.get(i));
            }
            outboxList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outboxList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        mail = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        inboxList = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        mail2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        dest = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        alert = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        draftList = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JTextArea();
        sendFromDraft = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        subject1 = new javax.swing.JTextField();
        dest1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alerte1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Icons/back.png")));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Messages");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        outboxList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        outboxList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        outboxList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                outboxListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(outboxList);

        mail.setColumns(20);
        mail.setRows(5);
        jScrollPane4.setViewportView(mail);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Outbox", jPanel3);

        inboxList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inboxList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        inboxList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                inboxListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(inboxList);

        mail2.setColumns(20);
        mail2.setRows(5);
        jScrollPane6.setViewportView(mail2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inbox", jPanel2);

        dest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("Icons/union.png")));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("Icons/send.png")));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        text.setColumns(20);
        text.setRows(5);
        jScrollPane3.setViewportView(text);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Icons/video-call.png")));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("To :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Subject :");

        subject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        alert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alert.setForeground(new java.awt.Color(204, 0, 0));
        alert.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(alert))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dest, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(subject))
                        .addGap(28, 28, 28)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(save)
                .addGap(26, 26, 26)
                .addComponent(send)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alert)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New", jPanel4);

        draftList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        draftList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        draftList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                draftListValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(draftList);

        text1.setColumns(20);
        text1.setRows(5);
        jScrollPane8.setViewportView(text1);

        sendFromDraft.setIcon(new javax.swing.ImageIcon(getClass().getResource("Icons/send.png")));
        sendFromDraft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendFromDraftMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Subject :");

        subject1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });

        dest1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("To :");

        alerte1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alerte1.setForeground(new java.awt.Color(204, 0, 0));
        alerte1.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alerte1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dest1)
                                .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(sendFromDraft)))
                .addGap(31, 31, 31))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dest1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendFromDraft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(alerte1)
                        .addGap(32, 32, 32))))
        );

        jTabbedPane1.addTab("Draft", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 750, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Home home=new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        if(jTabbedPane1.getSelectedIndex()==0){
            List<String> s = getOutboxMail();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < s.size(); i++) {
                model.addElement(s.get(i));
            }
            outboxList.setModel(model);
        }
        else if(jTabbedPane1.getSelectedIndex()==1){
            List<String> s = getInboxMail();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < s.size(); i++) {
                model.addElement(s.get(i));
            }
            inboxList.setModel(model);
        }
        else if(jTabbedPane1.getSelectedIndex()==3){
            List<String> s = getDraftMail();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < s.size(); i++) {
                model.addElement(s.get(i));
            }
            draftList.setModel(model);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void outboxListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_outboxListValueChanged
        // TODO add your handling code here:
        mail.setText("");
        String selectedMail=outboxList.getSelectedValue();
        //Lire le fichier et ajoute le dans la fenetre de lecture
         BufferedReader in = null;
        try {
            in = new BufferedReader(new FileReader("Ressources/outbox/" + selectedMail + ".txt"));
            String line;
            while ((line = in.readLine()) != null) {

                mail.append(line);
                mail.append("\n");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outboxListValueChanged

    private void inboxListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_inboxListValueChanged
        // TODO add your handling code here:
        mail2.setText("");
        String selectedMail=inboxList.getSelectedValue();
         BufferedReader in = null;
        try {
            in = new BufferedReader(new FileReader("Ressources/inbox/" + selectedMail + ".txt"));
            String line;
            while ((line = in.readLine()) != null) {

                mail2.append(line);
                mail2.append("\n");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inboxListValueChanged

    private void draftListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_draftListValueChanged
        // TODO add your handling code here:
        String selectedMail=draftList.getSelectedValue();
        
        //Lire le fichier et ajoute le dans la fenetre de lecture
         BufferedReader in = null;
         if(selectedMail!=null)
        try {
            in = new BufferedReader(new FileReader("Ressources/draft/" + selectedMail + ".txt"));
            String line;
            int i=0;
            while ((line = in.readLine()) != null) {
                if(i==0){
                    text1.setText("");
                }
                else if(i==1){
                    dest1.setText(line);
                }
                else if(i==2){
                    subject1.setText(line);
                }
                else {
                    text1.append(line);
                    text1.append("\n");
                }
                i++;
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_draftListValueChanged

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1ActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        
        String to=dest.getText();
        String suj=subject.getText();
        String mail=text.getText();
        
        DateFormat format = new SimpleDateFormat();
        Date date = new Date();
        String dat=date.toGMTString().subSequence(0, 11).toString();
        String hour=date.getHours()+":"+date.getMinutes()+":"+date.getSeconds();
        
        String time=(dat + " / "+hour);
        System.err.println(time);
        
        
        try {
            //Enregisrer au brouillons
            PrintWriter writer = new PrintWriter("Ressources/draft/"+suj+".txt", "UTF-8");
            
            writer.println(time);  //1
            writer.println(to);
            writer.println(suj);
            writer.println(mail);
            writer.close();
            alert.setText("Mail is saved");
            
            dest.setText("");
            subject.setText("");
            text.setText("");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMouseClicked

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        // TODO add your handling code here:
        String to=dest.getText();
        String suj=subject.getText();
        String mail=text.getText();
        
        DateFormat format = new SimpleDateFormat();
        Date date = new Date();
        String dat=date.toGMTString().subSequence(0, 11).toString();
        String hour=date.getHours()+":"+date.getMinutes()+":"+date.getSeconds();
        
        String time=(dat + " / "+hour);
        
        
        try {
            //Enregisrer au brouillons
            PrintWriter writer = new PrintWriter("Ressources/outbox/"+suj+".txt", "UTF-8");
            
            writer.println("Time :\t"+time);  //1
            writer.println("To :\t"+ to);
            writer.println("Subject :\t"+suj);
            writer.println("\n\t"+mail);
            writer.close();
            alert.setText("Mail is sent to "+to);
            
            dest.setText("");
            subject.setText("");
            text.setText("");
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendMouseClicked

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendActionPerformed

    private void sendFromDraftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendFromDraftMouseClicked
        // TODO add your handling code here:
        
        String to=dest1.getText();
        String suj=subject1.getText();
        String mail=text1.getText();
        
        DateFormat format = new SimpleDateFormat();
        Date date = new Date();
        String dat=date.toGMTString().subSequence(0, 11).toString();
        String hour=date.getHours()+":"+date.getMinutes()+":"+date.getSeconds();
        
        String time=(dat + " / "+hour);
        
        
        try {
            String selected=draftList.getSelectedValue();
            PrintWriter writer = new PrintWriter("Ressources/outbox/"+selected+".txt", "UTF-8");
            
            writer.println("Time :\t"+time);  //1
            writer.println("To :\t"+ to);
            writer.println("Subject :\t"+suj);
            writer.println("\n\t"+mail);
            writer.close();
            alerte1.setText("Mail is sent to "+to);
            
            dest1.setText("");
            subject1.setText("");
            text1.setText("");
            
            //Supprimer à partir de brouillons et refaraichir:
            System.err.println(selected+".txt");
            File file = new File("Ressources/draft/" +selected+".txt");
            file.delete();
            
            //Refraichir
            
           // this.setVisible(false);
            List<String> s = getDraftMail();
            DefaultListModel model = new DefaultListModel();
            for (int i = 0; i < s.size(); i++) {
                model.addElement(s.get(i));
            }
            draftList.setModel(model);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(DoctorContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendFromDraftMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorContact().setVisible(true);
            }
        });
    }

    private List<String> getInboxMail(){
        File repertoire = new File("Ressources/inbox");
        File[] listeFilePath = repertoire.listFiles();
        List<String> s = new ArrayList<String>();
        for (int i = 0, num = 0; i < listeFilePath.length; i++) {
            s.add(listeFilePath[i].getName().replaceAll(".txt", ""));
        }
        return s;
    }
    
    
    private List<String> getOutboxMail(){
        File repertoire = new File("Ressources/outbox");
        File[] listeFilePath = repertoire.listFiles();
        List<String> s = new ArrayList<String>();
        for (int i = 0, num = 0; i < listeFilePath.length; i++) {
            s.add(listeFilePath[i].getName().replaceAll(".txt", ""));
        }
        return s;
    }
    
    private List<String> getDraftMail(){
        File repertoire = new File("Ressources/draft");
        File[] listeFilePath = repertoire.listFiles();
        List<String> s = new ArrayList<String>();
        for (int i = 0, num = 0; i < listeFilePath.length; i++) {
            s.add(listeFilePath[i].getName().replaceAll(".txt", ""));
        }
        return s;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.JLabel alerte1;
    private javax.swing.JTextField dest;
    private javax.swing.JTextField dest1;
    private javax.swing.JList<String> draftList;
    private javax.swing.JList<String> inboxList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea mail;
    private javax.swing.JTextArea mail2;
    private javax.swing.JList<String> outboxList;
    private javax.swing.JButton save;
    private javax.swing.JButton send;
    private javax.swing.JButton sendFromDraft;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField subject1;
    private javax.swing.JTextArea text;
    private javax.swing.JTextArea text1;
    // End of variables declaration//GEN-END:variables
}
