/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gatewayguiswing;

import java.awt.BorderLayout;
import java.awt.Panel;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.chart.XYChart;
import javax.microedition.io.Connector;
import javax.microedition.io.StreamConnection;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author blunt
 */
public class ReadFromSensor extends javax.swing.JFrame {

    private static JFreeChart chart;
    private static XYSeries series = new XYSeries("Sensor Readings");
    private static XYSeriesCollection dataset = new XYSeriesCollection(series);
    static int x = 0;
    Panel window;
    Random r = new Random();

    private static String commande = "1";
    //Sensor Bluetooth Parameter
    private static Timer timer;
    private static OutputStream os = null;
    private static InputStream is = null;
    private static StreamConnection streamConnection = null;
    private static String hc05Url = "btspp://FCA89A001BBF:1;authenticate=false;encrypt=false;master=false";

    /**
     * Creates new form NewJFrame
     */
    public ReadFromSensor() {
        initComponents();
        window = new Panel();
        window.setSize(600, 400);
        window.setLayout(new BorderLayout());
        window.add(new ChartPanel(chart), BorderLayout.CENTER);
        Panel1.add(window);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jButton1.setText("Start");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            /*
            int number = r.nextInt(20);
            series.add(x++, number);
            window.repaint();*/

            streamConnection = (StreamConnection) Connector.open(hc05Url);
            if (streamConnection != null) {
                os = streamConnection.openOutputStream();
                is = streamConnection.openInputStream();
                os.write(commande.getBytes()); //49 en ASCII pour prendre les mesures de temperatures;50 pour ECG
                //Commence à recevoir from BT:
                System.err.println("Receiving ... ");
                int tempsDEcoute = 15;
                timer = new Timer();
                timer.scheduleAtFixedRate(new TimerTask() {
                    
                   
                    byte[] b = new byte[200];
                    String result = "";
                    int j = 0;
                    long t0 = System.currentTimeMillis();

                    @Override
                    public void run() {
                         
                        if (System.currentTimeMillis() - t0 > tempsDEcoute * 1000) {
                            try {
                                System.out.println("End Of Timer");
                                timer.cancel();
                                //Close stream
                                is.close();
                                os.write("0".getBytes()); //50 en ASCII
                                os.close();
                                streamConnection.close();
                            } catch (IOException ex) {
                                Logger.getLogger(ReadFromSensor.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {
                            
                            
                            try {
                                System.err.println("1");
                                is.read(b);
                                System.err.println("2");
                                result = new String(b);
                                System.out.println("receive from BT: " + result);
                                if (j != 0) {
                                    series.add(x++, Float.valueOf(result)+30);
                                    window.repaint();
                                }
                                j = j + 1;
                                //results.add(result);
                            } catch (IOException ex) {
                                Logger.getLogger(ReadFromSensor.class.getName()).log(Level.SEVERE, null, ex);
                            }
                          

                        }
                    }
                }, 0, 1000);

            }
        } catch (IOException ex) {
            Logger.getLogger(ReadFromSensor.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadFromSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadFromSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadFromSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadFromSensor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                chart = ChartFactory.createXYLineChart("Sensor Readings", "Time (seconds)", "Reading", dataset);
                new ReadFromSensor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
